### ISSUE TITLE
A way to add additional commands

### ISSUE THREAD

**Issue by spark706** [dzhavat/git-cheatsheet-inside-vs-code#15]
Is there a way to add additional commands  to this sheet?

**Comment by dzhavat** [comment]
Yes, you can fork the project, add the desired commands and make a Pull Request (PR) that I can merge to `main`.

Or you can write the commands you'd like to add and I'll do it myself :)

**Comment by spark706** [comment]
I'll fork and add my own.  The items I would like to add are specific to my use case and not a larger overall help.

**Comment by dzhavat** [comment]
Sounds great. In this case you'll need to build the extension yourself and install it manually in VS Code. Here's [some info](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) for how to do it. If you need help with anything, let me know.
